### ISSUE TITLE
Required complete Extension

### ISSUE THREAD

**Issue by rishabhchd19** [codefoxes/textlocal#1]
Where can I get a complete extension for textlocal?

**Comment by karthikax** [comment]
This github repository is composer package for Textlocal php class.
Textlocal php class with documentation is here: http://api.textlocal.in/docs/phpclass

**Comment by rishabhchd19** [comment]
Is it ready to install and no other files needed? Like Helper, Observer,
etc files?

**Comment by rishabhchd19** [comment]
Ok. Sry misunderstanding. I was looking and thinking towards the Magento 2
extension.
